version: "3.9"

services:
  redis:
    image: redis:${REDIS_VERSION:-alpine}
    container_name: redis
    restart: unless-stopped
    expose:
      - 6379
    networks:
      - cqt-net
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
    logging:
      options:
        max-size: "1g"

  geth:
    image: "us-docker.pkg.dev/covalent-project/network/bsp-geth:${BSP_GETH_VERSION:-latest}"
    container_name: execution
    restart: unless-stopped
    stop_grace_period: 1m
    env_file: [".env"]
    depends_on:
      - redis
    networks:
      - cqt-net
    ports:
      - 30303:30303/tcp # p2p
      - 30303:30303/udp # p2p
      - 8545:8545
      - 8551:8551
    volumes:
      - ./data/ethereum/:/data/.ethereum
      - ./scripts/start-geth.sh:/scripts/start-geth.sh:ro
      - ./secrets/jwt.hex:/jwt.hex
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    entrypoint: sh /scripts/start-geth.sh
    logging:
      options:
        max-size: "1g"

  lighthouse:
    image: sigp/lighthouse:${LIGHTHOUSE_VERSION:-latest}
    container_name: consensus
    restart: unless-stopped
    stop_grace_period: 1m
    networks:
      - cqt-net
    volumes:
      - ./data/lighthouse:/root/.lighthouse
      - ./scripts/start-lighthouse.sh:/scripts/start-lighthouse.sh:ro
      - ./secrets/jwt.hex:/jwt.hex
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 5052:5052
    env_file: [".env"]
    entrypoint: sh /scripts/start-lighthouse.sh
    logging:
      options:
        max-size: "1g"

  ewm-das:
    image: "us-docker.pkg.dev/covalent-project/network/ewm-das:${EWM_DAS_IPFS_VERSION:-stable}"
    volumes:
      - ./scripts/start-ipfs.sh:/scripts/start-ipfs.sh:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./secrets/proof.out:/proof.out:ro
      - ./ipfs:/root/.ipfs/
    container_name: ewm-das
    restart: on-failure
    env_file: [".env"]
    entrypoint: sh /scripts/start-ipfs.sh
    networks:
      - cqt-net
    ports:
      - "4001:4001"
      - "3001:3001"
      - "5080:5080"
    logging:
      options:
        max-size: "1g"

  agent:
    image: "us-docker.pkg.dev/covalent-project/network/bsp-agent:${BSP_AGENT_VERSION:-latest}"
    container_name: bsp-agent
    restart: unless-stopped
    depends_on:
      - redis
    volumes:
      - bsp-agent:/app/data
      - ./scripts/start-agent.sh:/scripts/start-agent.sh:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./block-ethereum.avsc:/app/codec/block-ethereum.avsc:ro
    entrypoint: sh /scripts/start-agent.sh
    env_file: [".env"]
    networks:
      - cqt-net
    ports:
      - "8080:8080"
    logging:
      options:
        max-size: "1g"

  restart-on-agent-failure:
    image: docker:latest
    container_name: restart-on-agent-failure
    restart: "no"
    depends_on:
      - agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./scripts/restart-on-agent-failure.sh:/scripts/restart-on-agent-failure.sh:ro
    entrypoint: sh /scripts/restart-on-agent-failure.sh

networks:
  cqt-net:
    name: cqt-net
    driver: bridge

volumes:
  bsp-agent: